### ISSUE TITLE
Latest

### ISSUE THREAD

**Issue by AdamKane41** [juliagoda/antimicro#25]
Visuals :-D

![1](https://user-images.githubusercontent.com/30092603/45251585-9aa5a700-b316-11e8-8389-7e8fcdb09f50.png)

![2](https://user-images.githubusercontent.com/30092603/45251586-9b3e3d80-b316-11e8-90a5-c82dbda90ac4.png)

![3](https://user-images.githubusercontent.com/30092603/45251587-9b3e3d80-b316-11e8-9522-e6ffdee9b995.png)

![4](https://user-images.githubusercontent.com/30092603/45251588-9b3e3d80-b316-11e8-839e-8b10f8da6819.png)

![5](https://user-images.githubusercontent.com/30092603/45251589-9bd6d400-b316-11e8-88e9-c9d64e3f2b40.png)

![6](https://user-images.githubusercontent.com/30092603/45251590-9bd6d400-b316-11e8-9d66-02aaef85e106.png)

It works great Thanks!

**Comment by juliagoda** [comment]
Thank you. It's hard for me to develop application at the moment because of duplicated lines of code, so as first I try to clean the code and to give refactoring a shot. If you notice something strange even during cleaning, will you let me know about this? It would be helpful.   

PS: I've fixed empty rows in Game Controller Mapping window and strange mapping for axes in the main window after my cleaning.

**Comment by AdamKane41** [comment]
Yeah no problem! I'LL keep you posted when i find stuff. 
Also my controller pic on the mapping screen is a custom made "ubuntu" flavored version, but here is my unbranded version for you... the one already in the app is lo-res and cheap looking.
peace

![controllemap](https://user-images.githubusercontent.com/30092603/45254012-0f400c00-b33e-11e8-9495-506e5509bcd0.png)
