### ISSUE TITLE
DEB file?

### ISSUE THREAD

**Issue by brylie** [juliagoda/antimicro#29]
Is there a DEB file available, or PPA for Ubuntu 18.04?

**Comment by sirlucjan** [comment]
As far as I know, no.

**Comment by brylie** [comment]
Okee dokee. I managed to find one on the Webupd8 team repo:

https://www.ubuntuupdates.org/package/webupd8/xenial/main/base/antimicro

Although it is not packaged for 18.04, it installed with no problem.

**Comment by pktiuk** [comment]
I would be convenient to have any usable .deb on release site.

**Comment by sirlucjan** [comment]
Then we're counting on you to do it :)!

**Comment by pktiuk** [comment]
Challenge accepted. :)

Currently I will try to add creating .deb to CmakeLists.txt.
Later I will think how to add it to release site (and maybe connect it with github actions).

**Comment by pktiuk** [comment]
I've added configuration for easy generating .deb files. https://github.com/juliagoda/antimicroX/pull/103
But I can't add from my repo new file to current release.

**Comment by juliagoda** [comment]
When have you added the changes? I don't see anything new in your repo since April 19th. You have this file locally on your system? I merged your changes into master. As far as I know changes to release page cannot be added by forks' authors. Everything new and about generating deb file will be added in next release soon. Editing current release doesn't have sense, because it doesn't have the changes in CMakeLists anyway, but in master since April 22th. "antimicroX-2.25 - juliagoda released this on 7 Jan · 95 commits to master since this release".

**Comment by pktiuk** [comment]
I was just experimenting with editing current release from my fork. 
As you said, fork's authors cannot edit release page, so this change should wait for next release.
