### ISSUE TITLE
uinput doesn't seem to work in 2.24.1

### ISSUE THREAD

**Issue by pouar** [juliagoda/antimicro#53]
seems to work in 2.24, though 2.24.1 seems to write garbage to the console that it was currently started on

**Comment by juliagoda** [comment]
1. Does your kernel have loaded uinput module?
2. Are you allowed to run /dev/uinput as user (ls -l /dev/uinput)?
3. The lines you are talking about... is just debugger, that writes messages about any warnings and informations (That's enough when someone will comment one line in CMakeLists file to turn it off, but I think, that it's more helpful for me and users to detect errors)

**Comment by pouar** [comment]
for the first 2, yes. Though for the 3rd, it's writing binary. Also, when I replaced the function UInputEventHandler::init() in eventhandlers/uinputeventhandler.cpp from 2.24.1 with the one from 2.24, uinput starts working again.

**Comment by pouar** [comment]
Also, replacing the function also causes the garbage to no longer being written to the console

**Comment by juliagoda** [comment]
I have to think about it more then... It's strange, because for me it starts and works after XTEST is turned off and UINPUT - on:
![2019-01-18-121555_1366x768_scrot](https://user-images.githubusercontent.com/24532426/51383945-29270200-1b1b-11e9-9c38-9bc24970b744.png)


1. What linux distribution are you using?
2. What is name of your kernel and version?
3. What shows "the garbage" - lines of results from console?
4. There is first example I found, that shows similar situation (of course it doesn't mean to be a fixed thing at the moment):
[Uinput doesn't work with Xorg](https://askubuntu.com/questions/1044526/uinput-doesnt-work-with-xorg) 
5. Could you try to run version 2.24 without replacing anything? Is it the same situation?

**Comment by pouar** [comment]
I think I figured out the problem. You might be passing device to UInputEventHandler::initDevice by value instead of by reference. This patch seems to fix it.
```Diff
diff --git a/src/eventhandlers/uinputeventhandler.cpp b/src/eventhandlers/uinputeventhandler.cpp
index fe15ecf..e2fbaee 100755
--- a/src/eventhandlers/uinputeventhandler.cpp
+++ b/src/eventhandlers/uinputeventhandler.cpp
@@ -119,7 +119,7 @@ bool UInputEventHandler::init()
 }
 
 
-void UInputEventHandler::initDevice(int device, QString name, bool& result)
+void UInputEventHandler::initDevice(int& device, QString name, bool& result)
 {
     device = openUInputHandle();
 
diff --git a/src/eventhandlers/uinputeventhandler.h b/src/eventhandlers/uinputeventhandler.h
index a6061fd..1227b0a 100755
--- a/src/eventhandlers/uinputeventhandler.h
+++ b/src/eventhandlers/uinputeventhandler.h
@@ -80,7 +80,7 @@ private:
 
     bool cleanupUinputEvHand();
     void testAndAppend(bool tested, QList<unsigned int>& tempList, unsigned int key);
-    void initDevice(int device, QString name, bool& result);
+    void initDevice(int& device, QString name, bool& result);
 
 };
```

**Comment by juliagoda** [comment]
I've added the changes. Is it working now or there are other problems with uinput?

**Comment by pouar** [comment]
so far no, although Turbo doesn't seem to work, but I should probably open another issue for that (and the fix as I came up with one)

**Comment by juliagoda** [comment]
ok, so I close it
