### ISSUE TITLE
Create windows builds

### ISSUE THREAD

**Issue by wingedonezero** [juliagoda/antimicro#56]
Is there any chance of getting a build of the latest for my windows box? Compiling source on linux is easy and fine but for windows its a pain to figure out.

**Comment by juliagoda** [comment]
Yes and I understand that nowadays applications should run on multiple platforms. Give me some time for that and other ideas/lacks/issues, because I have to create and describe application for dissertation by 15 March. All ideas I have noted and remember about them. In the meantime I am trying to clean code and increase modularity
