### ISSUE TITLE
Clearing a mapping doesn't work

### ISSUE THREAD

**Issue by maxigaz** [juliagoda/antimicro#69]
**Edit**: I've just realised by visiting the main page of this project that it has been abandoned. Since I've already submitted it, I'll just leave the report here in case someone who wants to pick up development again sees it.

At any rate, @juliagoda, if you're reading this: I'd like to thank you for maintaining antimicro for the past several months. Just like in other FOSS projects, fixing various bugs (no matter how small they were) really made a difference in making antimicro more usable and, since I've used it regularly, it meant a lot to me. I wish you the best from now on.

---------------

When trying to clear a button mapping by clicking on NONE in the screenshot below, the outcome can be either of the following:

- In a *new* profile: nothing happens.
- In a *previously saved* profile: antimicro freezes.

![antimicro_20190626_151527](https://user-images.githubusercontent.com/10419911/60183851-56dd4900-9827-11e9-9f00-1966fa2e4fa1.png)

Here's the output of `ulimit -c unlimited && antimicro` that is printed when the freeze occurs.

```
Debug: "antimicro antimicro" ((null):0, (null))
Debug: antimicro antimicro ((null):0, (null))
Debug: class of window now:  "antimicro antimicro"
 ((null):0, (null))
Debug: WIN: 0x "5a00021" ((null):0, (null))
Debug: "As last gamepad button has been set \"Stick 1: Button Down\" " ((null):0, (null))
Debug: title of window now:  "As last gamepad button has been set \"Stick 1: Button Down\" "
 ((null):0, (null))
Debug: WINDOW CLASS:  "antimicro antimicro" ((null):0, (null))
Debug: WINDOW NAME:  "As last gamepad button has been set \"Stick 1: Button Down\" " ((null):0, (null))
Debug: WINDOW IN FOCUS:  "94371873" ((null):0, (null))
Debug: window profile assignments size:  2
 ((null):0, (null))
Debug: checkForTitleChange:  true ((null):0, (null))
Warning: QMetaMethod::invoke: Dead lock detected in BlockingQueuedConnection: Receiver is JoyButton(0x560f35ee5990) ((null):0, (null))
```

On the other hand, if I try clearing a mapping in the main window (right click → Clear), that only seems to work if I'm in a new profile and I push the relevant button on the gamepad after selecting Clear. Otherwise, nothing happens.

System info:

- Operating System: Manjaro Linux KDE
- Antimicro Version: 2.24.1
- Qt Version: 5.12.3
- Kernel Version: 5.1.8-1-MANJARO x86_64

**Comment by juliagoda** [comment]
Thank you for your words. Antimicro is going to be too big to me, so I decided to change project. At first glance it might seem strange, but to work perfectly this program needs to have constant bug fixes (even due to Qt5 library code changes), added translations in foreign languages, written tests, created menu and window icons, created and tested new functionalities, improved CMakeLists file for Windows, written full documentation for users as well as for developers, code refactoring and probably more. Continuation of the program became too hard for me, because I was developing it mainly on my own. Before I finished doing one thing, another thing needed immediate intervention. I hope the answer will be understood, and I'm sorry it came out that way. Maybe the situation will change someday

**Comment by juliagoda** [comment]
#74

**Comment by juliagoda** [comment]
Does project from last commit work properly? Does the bug still appear?

**Comment by maxigaz** [comment]
> Does project from last commit work properly? Does the bug still appear?

After a quick test, I can confirm that it works and the bug is no longer there. Thank you, @adelq and @juliagoda!

**Comment by maxigaz** [comment]
After some further usage, I experience #64 again (see [this](https://github.com/juliagoda/antimicro/issues/64#issuecomment-480808145) and [this](https://github.com/juliagoda/antimicro/issues/64#issuecomment-487060353) comment on how I reproduce it.
